# Generated by Django 3.1.4 on 2020-12-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_registro_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='correo',
            field=models.EmailField(max_length=60, verbose_name='correo'),
        ),
    ]
